name: ak_sandik
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  buttons_tabbar: ^1.3.8
  cached_network_image: ^3.3.1
  camera: ^0.10.5+9
  cupertino_icons: ^1.0.6
  exif: ^3.3.0
  flutter_document_scanner: ^1.1.0
  flutter_image_compress: ^2.2.0
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  http: ^1.2.1
  image: ^4.1.7
  image_picker: ^1.0.7
  image_cropper: ^5.0.1
  insta_image_viewer: ^1.0.2
  intl: ^0.19.0
  loading_animation_widget: ^1.2.0+4
  photo_view: ^0.14.0
  toast: ^0.3.0
  vertical_scroll_tabbar: ^0.0.4+4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  image_path_android: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/icon/background.png"
  adaptive_icon_foreground: "assets/icon/foreground.png"
  remove_alpha_ios: true
  background_color_ios: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo/
    - assets/images/header/


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat.ttf
